# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG SOLUTION_NAME=api.Identity.Api.slnf
WORKDIR /project

# copy and restore
COPY api/*.sln .
COPY api/${SOLUTION_NAME} .
COPY api/src/Identity.Api/*.csproj ./src/Identity.Api/
COPY api/src/SmartHome.ServiceDefaults/*.csproj ./src/SmartHome.ServiceDefaults/
RUN dotnet restore ${SOLUTION_NAME}

# copy and publish
COPY api/src/Identity.Api ./src/Identity.Api/
COPY api/src/Shared ./src/Shared/
COPY api/src/SmartHome.ServiceDefaults ./src/SmartHome.ServiceDefaults/
WORKDIR /project/src/Identity.Api
RUN dotnet publish -c Release -o /app --no-restore

# final image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
# configure ENV ASPNETCORE_URLS=https://+:10103 if use WebHost.CreateDefaultBuilder()
ENV ASPNETCORE_HTTP_PORTS=10103
LABEL author=LWB
WORKDIR /app
COPY --from=build /app ./
EXPOSE 10103
ENTRYPOINT ["dotnet", "Identity.Api.dll"]