FROM node:22.14.0 AS builder
WORKDIR /project
COPY web .
#RUN npm install -g cnpm --registry=https://registry.npmmirror.com
#RUN cnpm install
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /project/dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf